.github/CODEOWNERS

I'm hoping that this will mean that any senior developer can do the required review

team code ownership

---

.github/workflows/editor-config-checker.yml

Hopefully, this will block pull requests that don't conform to our editor config.

Add Editor Config Checker Workflow

---

src/changelog.md

Reduces work when doing releases

Remove [ ] from changelog

---

src/Addons/34thPRC_ArmourStandard/data/mkiv/config_vehicles.hpp
src/Addons/34thPRC_ArmourStandard/data/mkiv/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_glasses.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_vehicles.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/odst/config_vehicles.hpp
src/changelog.md

I also made simular changes to spartan armour

odst backpack display name fix

---

src/Addons/sc_uniforms/config.cpp
src/changelog.md

fix sc_uniforms popup on startup

---

src/Addons/34thPRC_ArmourStandard/data/mkvb/config_vehicles.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_weapons.hpp
src/changelog.md

We have given everyone enough time to fix their load-outs, now we remove it
Closes #110

Remove old stuff

---

src/Addons/SEC_GuestPack/config.cpp
src/Addons/SEC_GuestPack/data/MKV/Gray_MKV_Shoulders_CO.paa
src/Addons/SEC_GuestPack/data/MKVB/Gold_MKVB_Visor_CO.paa
src/Addons/SEC_GuestPack/data/MKVB/MKVBHelmetOutline.paa
src/Addons/SEC_GuestPack/data/MKVB/Steel_MKVB_Helmet_CO.paa
src/Addons/SEC_GuestPack/data/MKVB/Steel_MKV_Lower_CO.paa
src/Addons/SEC_GuestPack/data/MKVB/Steel_MKV_Upper_CO.paa
src/changelog.md

Originally as a PBO from Cain, I unpacked it so that Git would like it better

Add SEC_GuestPack

---

.gitattributes
src/Addons/34thPRC_LoadingScreens/$PREFIX$
src/Addons/34thPRC_LoadingScreens/config.cpp
src/Addons/34thPRC_LoadingScreens/data/company_emblem.paa
src/Addons/34thPRC_LoadingScreens/data/loading1.jpg
src/Addons/34thPRC_LoadingScreens/data/loading2.jpg
src/Addons/34thPRC_LoadingScreens/data/loading3.jpg
src/Addons/34thPRC_LoadingScreens/data/loading4.jpg
src/Addons/34thPRC_LoadingScreens/data/loading5.jpg
src/Addons/34thPRC_LoadingScreens/data/splash_screen.paa
src/changelog.md

Loading Screens

---

src/Addons/SEC_GuestPack/config.cpp
src/changelog.md

SEC Guest Armour Patch

---

src/Addons/34thPRC_AceArsenalExtended/config.cpp
src/Addons/34thPRC_ArmourStandard/data/marines2/config_vehicles.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/urban/Blue_LowerBDU.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/urban/Blue_TrooperCollar.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/urban/Blue_UpperBDU.paa
src/changelog.md

Needs Ace Arsenal Extended config

Urban blue camo

---

build.ps1

build script improvements

---

src/Addons/34thPRC_ArmourStandard/data/mkiv/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_glasses.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/odst/config_vehicles.hpp
src/Addons/34thPRC_ArmourStandard/data/odst/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/weapons/grl45/config_magazines.hpp

code style fixes

---

src/Addons/34thPRC_AceArsenalExtended/config.cpp
src/Addons/34thPRC_ArmourStandard/data/marines2/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/visor/HelmetAccessories_Blue_CA.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/visor/HelmetAccessories_Green_CA.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/visor/HelmetAccessories_Orange_CA.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/visor/HelmetAccessories_Purple_CA.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/visor/HelmetAccessories_Red_CA.paa
src/changelog.md

5 colors for the eye piece and visor glasses on the marine helmet.

Visor glasses and eye piece varients

---

doc/Code_Style.md

Updates, clarifications, and new information for the Code_Style.md file.

Updated Code_Style.md

---

src/Addons/34thPRC_Vehicles/config.cpp
src/changelog.md

Add missing scorpion entries to allow them to be used in zeus

---

src/Addons/34thPRC_Overrides/data/vehicles/springbok/config_vehicles.hpp
src/changelog.md

LR Radio in Springbok Cmdr Seat

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/JFO/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/JFO/jfo_helmet_arctic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/JFO/jfo_helmet_arid.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/JFO/jfo_helmet_tropic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/JFO/jfo_helmet_urban.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/JFO/jfo_helmet_woodland.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/config_weapons.hpp
src/changelog.md

JFO Helemts done up with AAX support and 5 camos.
Closes #294

JFO for Marines/ODSTs

---

src/Addons/34thPRC_Overrides/config.cpp
src/Addons/34thPRC_Overrides/data/weapons/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/weapons/srs99am/config_weapons.hpp
src/changelog.md

Using magazineWell structure I added the 19th's SRS99am ammo to the NavSpecWep SRS99am. Closes #205

NavSpecWep SRS99am w/ 19th Ammo

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/CQC/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/CQC/cqc_helmet_arctic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/CQC/cqc_helmet_arid.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/CQC/cqc_helmet_tropic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/CQC/cqc_helmet_urban.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/CQC/cqc_helmet_woodland.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/config_weapons.hpp
src/changelog.md

5 camo variant for CQC for Marines/ODSTs
closes #293

CQC 4 Marines/ODSTs

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/grenadier/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/scout/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/scout/scout_helmet_arctic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/scout/scout_helmet_arid.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/scout/scout_helmet_tropic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/scout/scout_helmet_urban.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/scout/scout_helmet_woodland.paa
src/changelog.md

Scout Helmet made for marines and odsts
Closes #307

Scout Helmet

---

src/Addons/34thPRC_ArmourStandard/data/mkiv/config_vehicles.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_vehicles.hpp
src/Addons/34thPRC_Overrides/data/backpacks/exosuit/config_vehicles.hpp
src/changelog.md

MKIV, MKV(B), and Exosuit shoulders: added config for ace_gunbag

Spartan Gunbags

---

src/Addons/34thPRC_Overrides/data/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/mvi/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/mvi_cnm/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/mvi_hul/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/mvi_ul/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/mvi_ul_cnm/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/mvi_ul_hul/config_weapons.hpp
src/changelog.md

Added thermal modes to all MVI tagged NVGs via override to cancel out changed from 1st MEU Aux Mod.

MVI Thermals

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_custom/odst2/group1/config.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/arctic/shewolf_odst_helmet_arctic.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/arid/shewolf_odst_helmet_arid.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/tropic/shewolf_odst_helmet_tropic.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/urban/shewolf_odst_helmet_urban.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/visor/shewolf_odst_visor.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/woodland/shewolf_odst_helmet_woodland.paa
src/changelog.md

Shewolf's custom helm, in 5 camo variants with aax support.

Shewolf Custom ODST Helm

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/pilot/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/pilot/pilot_helmet_arctic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/pilot/pilot_helmet_arid.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/pilot/pilot_helmet_tropic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/pilot/pilot_helmet_urban.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/pilot/pilot_helmet_woodland.paa
src/changelog.md

Pilot helmet for marines and odsts
closes #318

pilot for marines and odsts

---

src/Addons/34thPRC_ArmourCustom/data/marines2/jade/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/marines2/jade/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/marines2/jade/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/marines2/jade/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/marines2/jade/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/woodland/config_weapons.hpp
src/changelog.md

Shortened uniform names and fixed incorrect displayName on one 'Jade' custom armor variant.

Shortened uniform names

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/recon/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/recon/recon_helmet_arctic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/recon/recon_helmet_arid.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/recon/recon_helmet_tropic.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/recon/recon_helmet_urban.paa
src/Addons/34thPRC_ArmourStandard/data/marines2/specialist_helmets/recon/recon_helmet_woodland.paa
src/changelog.md

Recon for non spartans with aax support
closes #322

Recon for Marines and ODST

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/vehicles/armour_standard/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/vehicles/armour_standard/mkvb/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/vehicles/armour_standard/mkvb/shoulders/config.hpp
src/Addons/34thPRC_ArmourStandard/data/mkvb/config_vehicles.hpp
src/changelog.md

AAX for MKVB Shoulders

---

src/Addons/34thPRC_LoadingScreens/config.cpp
src/Addons/34thPRC_LoadingScreens/data/loading9.jpg
src/changelog.md

Overwrote all of 1st MEU's loading texts and put in our own. Will add more as they come in.
closes #288

Loading Texts, and New Loading Image

---

doc/Code_Style.md
doc/Getting_Started.md
doc/Senior_Developer.md

and swap to - for bullet points
Updated due to #327

update release steps

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_custom/odst2/group1/config.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/arctic/jfo_helmet_arctic.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/arid/jfo_helmet_arid.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/tropic/jfo_helmet_tropic.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/urban/jfo_helmet_urban.paa
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/luther/woodland/jfo_helmet_woodland.paa
src/changelog.md

Did up the config for Luther's Custom helm with his supplied .paa files. They look okay but if I find the time I might redo the paa files for him.
related to #197

Luther Custom Helmet

---

.gitignore

I have had enough of random noise in my changes being left in my local

git ignore for hemtt bits

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/pilot/config.hpp
src/Addons/34thPRC_ArmourStandard/config.cpp
src/Addons/34thPRC_ArmourStandard/data/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/pilot/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/pilot/arctic/pilot_helmet_ext.paa
src/Addons/34thPRC_ArmourStandard/data/pilot/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/pilot/arid/pilot_helmet_ext.paa
src/Addons/34thPRC_ArmourStandard/data/pilot/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/pilot/pilot_helmet_addons.paa
src/Addons/34thPRC_ArmourStandard/data/pilot/pilot_helmet_visor.paa
src/Addons/34thPRC_ArmourStandard/data/pilot/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/pilot/tropic/pilot_helmet_ext.paa
src/Addons/34thPRC_ArmourStandard/data/pilot/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/pilot/urban/pilot_helmet_ext.paa
src/Addons/34thPRC_ArmourStandard/data/pilot/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/pilot/woodland/pilot_helmet_ext.paa
src/changelog.md

34th textures for UNSC Foundries IHADSS pilot helm. AAX support included.
closes #29

34th IHADSS

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_infos/weapons/external/optre_nvgs/config.hpp
src/Addons/34thPRC_Overrides/data/nvgs/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/hul3/config_weapons.hpp
src/Addons/34thPRC_Overrides/data/nvgs/hul3g/config_weapons.hpp
src/changelog.md

thermal vision for HUL Gen 3

---

src/Addons/34thPRC_ArmourStandard/data/odst2/backpacks/s9solajumpjet/config_vehicles.hpp
src/changelog.md

added grappling hook functionality to an alt version of our jump-jet.

Grapplinghook Jump-Jet

---

src/changelog.md

Add missing changelog entry

---

src/changelog.md

Not going to bother putting this one in the release

I am rushign and making more mistakes

---

src/Addons/34thPRC_ArmourCustom/data/odst2/ambrose/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/ambrose/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/ambrose/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/ambrose/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/ambrose/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/shewolf/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/vasya/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/vasya/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/vasya/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/vasya/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/vasya/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/yandere/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/yandere/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/yandere/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/yandere/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourCustom/data/odst2/yandere/woodland/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/odst2/arctic/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/odst2/arid/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/odst2/tropic/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/odst2/urban/config_weapons.hpp
src/Addons/34thPRC_ArmourStandard/data/odst2/woodland/config_weapons.hpp
src/changelog.md

fix depolarisation error 

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/vehicles/armour_standard/odst/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_custom/marines2/group1/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_custom/odst2/group1/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/odst2/config.hpp
src/changelog.md

All names changed

---

src/Addons/34thPRC_Overrides/data/weapons/railgun/config_ammo.hpp
src/changelog.md

Works closer to the intended request.

Balance pass

---

src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_custom/marines2/group1/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_custom/odst2/group1/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/marines2/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/odst2/config.hpp
src/Addons/34thPRC_AceArsenalExtended/data/aax_models/weapons/armour_standard/pilot/config.hpp
src/Addons/34thPRC_ArmourStandard/data/camo_pattern/Arctic.paa
src/Addons/34thPRC_ArmourStandard/data/camo_pattern/Arid.paa
src/Addons/34thPRC_ArmourStandard/data/camo_pattern/Night.paa
src/Addons/34thPRC_ArmourStandard/data/camo_pattern/Tropic.paa
src/Addons/34thPRC_ArmourStandard/data/camo_pattern/Urban.paa
src/Addons/34thPRC_ArmourStandard/data/camo_pattern/Woodland.paa
src/changelog.md

AAX Camo Colors Selection

---

.github/workflows/hemtt-build.yml
.github/workflows/make-release.yml
.github/workflows/prep-release.yml

make release github action

---

.github/workflows/greetings.yml
meta/doc/Getting_Started.md

onboarding improvements

---

.github/workflows/stale.yml

stale branches checker

---

addons/functions/$PREFIX$
addons/functions/M99A2S3A/a2s3a_postinit.sqf
addons/functions/M99A2S3A/a2s3a_preinit.sqf
addons/functions/M99A2S3A/a2s3a_prestart.sqf
addons/functions/M99A2S3A/config.cpp
addons/functions/M99A2S3A/functions/ace/airburst_ammunition_handler.sqf
addons/functions/M99A2S3A/functions/conditions.sqf
addons/functions/M99A2S3A/functions/fired_eh.sqf
addons/functions/M99A2S3A/functions/handle_is_burst.sqf
addons/functions/M99A2S3A/functions/keybind.sqf
addons/functions/M99A2S3A/functions/lase_distance_infantry.sqf
addons/functions/M99A2S3A/functions/lase_distance_vehicle.sqf
addons/functions/M99A2S3A/functions/set_fuse_distance.sqf
addons/functions/M99A2S3A/functions/ui/onConfirm.sqf
addons/functions/M99A2S3A/functions/ui/onExit.sqf
addons/functions/M99A2S3A/functions/ui/onLoad.sqf
addons/functions/MusicRadio/$PREFIX$
addons/functions/MusicRadio/config.cpp
addons/functions/config.cpp
changelog.md

Fixed file paths to function with Hemtt expectations for scripting.

fix m99 + music scripts when built with HEMTT

---

addons/ace_arsenal_extended/data/aax_models/weapons/armour_standard/config.hpp
addons/ace_arsenal_extended/data/aax_models/weapons/armour_standard/crewman/config.hpp
addons/armour_standard/data/crewman/config_weapons.hpp
changelog.md

AAX for the crewman helmets

---

addons/markers/$PREFIX$
changelog.md

Changes $PREFIX$ to correct internal name for markers pbo

fix prefix for markers

---

addons/vehicles/data/scorpion/config_vehicles.hpp
changelog.md

Fix scorpion textures
